# Generated by Django 2.1 on 2018-08-27 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journalpath', '0002_auto_20180825_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='learned',
            field=models.BooleanField(default=1, verbose_name='Learned'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsession',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='emoji',
            field=models.CharField(max_length=16, verbose_name='Emotion'),
        ),
    ]
