# Generated by Django 2.1 on 2018-08-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalpath', '0004_auto_20180827_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='difficulty',
            field=models.IntegerField(default=0, verbose_name='Difficulty'),
            preserve_default=False,
        ),
    ]
