# Generated by Django 2.1 on 2018-08-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalpath', '0005_catalog_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='Notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='self_appraisal',
            field=models.IntegerField(default=0, verbose_name='Self Appraisal'),
            preserve_default=False,
        ),
    ]
